### ISSUE TITLE
Broke on kernel 6.3.1

### ISSUE THREAD

**Issue by amithiel** [lwfinger/rtl8852au#46]
Make: 

```
#rm -f .symvers.8852au
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.3.1-arch1-1/build M=/home/eggzaile/rtl8852au  modules
  CC [M]  /home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.o
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_ch_switch_notify’:
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c:468:17: error: too few arguments to function ‘cfg80211_ch_switch_started_notify’
  468 |                 cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/eggzaile/rtl8852au/include/osdep_service_linux.h:100,
                 from /home/eggzaile/rtl8852au/include/osdep_service.h:42,
                 from /home/eggzaile/rtl8852au/include/drv_types.h:25,
                 from /home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:8392:6: note: declared here
 8392 | void cfg80211_ch_switch_started_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c:484:9: error: too few arguments to function ‘cfg80211_ch_switch_notify’
  484 |         cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
./include/net/cfg80211.h:8375:6: note: declared here
 8375 | void cfg80211_ch_switch_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_get_chbwoff_from_cfg80211_chan_def’:
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c:6263:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
 6263 |                 *ht = 0;
      |                 ~~~~^~~
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c:6265:9: note: here
 6265 |         case NL80211_CHAN_WIDTH_20:
      |         ^~~~
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c: At top level:
/home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.c:10612:1: fatal error: opening dependency file /home/eggzaile/rtl8852au/os_dep/linux/.ioctl_cfg80211.o.d: Permission denied
10612 | }
      | ^
compilation terminated.
make[2]: *** [scripts/Makefile.build:252: /home/eggzaile/rtl8852au/os_dep/linux/ioctl_cfg80211.o] Error 1
make[1]: *** [Makefile:2025: /home/eggzaile/rtl8852au] Error 2
make: *** [Makefile:636: modules] Error 2
```

**Comment by lwfinger** [comment]
That was my bad. I fixed it here, but forgot to push the fix. Try it again after another pull.

**Comment by jschwender** [comment]
with current kernel 6.3.5 still broken. where can i get the fix please?
